#!/bin/bash

v1=0
v2=0

for (( i=0; i<100; i++))
do
    response=`curl -s go-demo.example.com |grep -c v1`

    v1=`expr $v1 + $response`
    v2=`expr $v2 + 1 - $response`

done

echo "v1:$v1, v2:$v2"

